from __future__ import annotations

from typing import TYPE_CHECKING

from fullflow.System import Component, State

if TYPE_CHECKING:
    from fullflow.System import Network


class SimpleIsothermalTank(Component):
    """
    Isothermal liquid tank with optional hydrostatic head calculation.

    `SimpleTank` represents a tank whose pressure is prescribed and
    whose thermodynamic state is assumed constant. The component does not solve
    any conservation equations and is typically used as a simple fluid source,
    sink, or storage volume in steady-state analyses.

    When a liquid height is provided, the hydrostatic head pressure is computed
    from the liquid density and gravitational acceleration.

    Relations
    ---------
    Hydrostatic head pressure:

    `head_pressure = density * g * liquid_height`

    Parameters
    ----------
    name : str
        Component name.
    network : Network
        Network that owns this component.
    pressure : State
        Tank pressure [Pa].
    temperature : State, optional
        Tank temperature [K].
    liquid_height : State, optional
        Liquid column height above the outlet reference elevation [m].
    gravitation_acceleration : State or float, optional
        Gravitational acceleration [m/s^2]. Defaults to standard gravity.
    head_pressure : State, optional
        Hydrostatic pressure generated by the liquid column [Pa].
    internal_energy : State, optional
        Liquid specific internal energy [J/kg].
    density : State, optional
        Liquid density [kg/m^3].
    mass_flow_out : State, optional
        Tank discharge mass flow rate [kg/s].
    """

    def __init__(self, 
                 name: str,
                 network: Network,
                 pressure: State,
                 temperature: State | None = None,
                 liquid_height: State | None = None,
                 gravitation_acceleration: State | None = 9.80665,
                 head_pressure: State | None = None,
                 internal_energy: State | None = None,
                 density: State | None = None,
                 mass_flow_out: State | None = None):
        self.setup()


    def evaluate_states(self):
        if self.liquid_height.is_assigned:
            self.head_pressure.value = (self.density.value 
                                        * self.gravitational_acceleration.value 
                                        * self.liquid_height.value)
            
            


class PressurizedTank(Component):
    """
    Pressurized liquid tank with ullage collapse continuity.

    `PressurizedTank` represents a liquid storage tank pressurized by a gas
    ullage. The tank pressure is solved such that the change in ullage volume
    caused by liquid discharge is balanced by incoming pressurant mass.

    This formulation is useful for modeling regulated pressurization systems
    where a pressurant gas replaces discharged liquid volume.

    Residuals
    ---------
    ullage_continuity : float
        Enforces pressurant mass conservation:

        `mass_flow_in
        - collapse_factor
        * pressurant_density
        * mass_flow_out
        / liquid_density = 0`

    The collapse factor allows the user to account for non-ideal ullage
    behavior, tank collapse, or empirical corrections.

    Relations
    ---------
    Hydrostatic head pressure:

    `head_pressure = liquid_density * g * liquid_height`

    Iteration Variables
    -------------------
    pressure : State
        Tank pressure.

    Parameters
    ----------
    name : str
        Component name.
    network : Network
        Network that owns this component.
    pressure : State
        Tank pressure [Pa].
    pressurant_density : State
        Pressurant gas density [kg/m^3].
    liquid_density : State
        Liquid density [kg/m^3].
    collapse_factor : State or float, optional
        Empirical ullage collapse factor [-]. Defaults to 1.
    ullage_temperature : float, optional
        Pressurant ullage temperature [K].
    liquid_temperature : float, optional
        Bulk liquid temperature [K].
    liquid_height : State, optional
        Liquid column height above the outlet reference elevation [m].
    gravitation_acceleration : State or float, optional
        Gravitational acceleration [m/s^2]. Defaults to standard gravity.
    head_pressure : State, optional
        Hydrostatic pressure generated by the liquid column [Pa].
    pressurant_internal_energy : State, optional
        Pressurant specific internal energy [J/kg].
    liquid_internal_energy : State, optional
        Liquid specific internal energy [J/kg].
    liquid_enthalpy : State, optional
        Liquid specific enthalpy [J/kg].
    mass_flow_in : State, optional
        Pressurant mass flow rate entering the tank [kg/s].
    mass_flow_out : State, optional
        Liquid mass flow rate leaving the tank [kg/s].
    """

    def __init__(self, 
                 name: str, 
                 network: Network, 
                 pressure: State, 
                 pressurant_density: State, 
                 liquid_density: State, 
                 collapse_factor: State | float | None = 1, 
                 ullage_temperature: float | None = None, 
                 liquid_temperature: float | None = None, 
                 liquid_height: State | None = None, 
                 gravitation_acceleration: State | None = 9.80665, 
                 head_pressure: State | None = None, 
                 pressurant_internal_energy: State | None = None, 
                 liquid_internal_energy: State | None = None,
                 liquid_enthalpy: State | None = None,
                 mass_flow_in: State | None = None,
                 mass_flow_out: State | None = None):
        self.setup()

    def evaluate_states(self):
        if self.liquid_height.is_assigned:
            self.head_pressure.value = (self.density.value 
                                        * self.gravitational_acceleration.value 
                                        * self.liquid_height.value)


    @property
    def iteration_variables(self) -> list[State]:
        return [self.pressure]
    
    @property
    def residuals(self) -> list[float]:
        return [self.mass_flow_in.value 
                - self.collapse_factor.value * self.pressurant_density.value
                * self.mass_flow_out.value / self.liquid_density.value]